import React, { useState, useEffect } from 'react';
import { useLanguage } from '../context/LanguageContext';
import { getTermsPageStrings } from '../lib/sanity';

const FALLBACK_SECTIONS = [
  {
    sectionHeading: 'Explicit Content Disclaimer',
    sectionBody:
      'By using FIREWALL Cafe, you acknowledge that search results may include explicit or sensitive content generated by other users. FIREWALL Cafe is not responsible for the content of search queries submitted by users or the results returned by third-party search engines.',
  },
  {
    sectionHeading: 'Privacy Policy',
    sectionBody:
      'FIREWALL Cafe collects anonymized search data including search terms, timestamps, and approximate geographic location for research purposes. No personally identifiable information is stored. By using this service you consent to the collection of this anonymized data.',
  },
];

function TermsAndConditions() {
  const { language } = useLanguage();
  const [strings, setStrings] = useState({
    pageHeading: 'Terms and Conditions',
    pageHeadingZh: '条款和条件',
    sections: FALLBACK_SECTIONS,
  });

  useEffect(() => {
    async function fetchStrings() {
      try {
        const data = await getTermsPageStrings(language);
        if (data) {
          setStrings({
            pageHeading: data.pageHeading || 'Terms and Conditions',
            pageHeadingZh: data.pageHeadingZh || '条款和条件',
            sections: data.sections?.length ? data.sections : FALLBACK_SECTIONS,
          });
        }
      } catch (_) {}
    }
    fetchStrings();
  }, [language]);

  return (
    <main className="flex flex-col items-center bg-white w-full is-full-width-content">
      {/* Page heading */}
      <div className="flex flex-col items-center justify-center pt-[120px] pb-[80px] w-full px-8">
        <div className="font-bitmap-song text-center">
          <h1 className="font-display-01 leading-tight tracking-[2.16px] text-black">
            {strings.pageHeading}
          </h1>
          <div className="font-display-01 leading-tight tracking-[2.16px] text-red-600">
            {strings.pageHeadingZh}
          </div>
        </div>
      </div>

      {/* Content sections */}
      <div className="flex flex-col gap-[60px] items-start w-full max-w-[720px] px-8 pb-[120px]">
        {strings.sections.map((section, index) => (
          <React.Fragment key={index}>
            {index > 0 && <hr className="w-full border-t border-[#b9c0c7]" />}
            <div className="flex flex-col gap-6 w-full">
              <h2 className="font-bold text-[22px] leading-[1.5] text-black">
                {section.sectionHeading}
              </h2>
              <p className="text-[17px] leading-[1.5] text-black whitespace-pre-line">
                {section.sectionBody}
              </p>
            </div>
          </React.Fragment>
        ))}
      </div>
    </main>
  );
}

export default TermsAndConditions;
